### ISSUE TITLE
Use for other projects?

### ISSUE THREAD

**Issue by julien-f** [zeit/err-redirect#2]
I like the simplistic but efficient approach of this service :)

Would it be possible to use it for other projects?
Perhaps by using a `/:user/:project/:error` URL?

**Comment by Qix-** [comment]
We agree :) I'll get to this today.

**Comment by Qix-** [comment]
Hey @julien-f - just deployed the fix for this.

You'll be able to use the existing URLs to automatically go to our ZEIT error pages, or you can add your own `user/repo/errorcode` which will redirect to your `user/repo/blob/master/errors/errorcode.md` file. :)

Thanks for the suggestion!
