### ISSUE TITLE
Open up usage for other orgs & projects?

### ISSUE THREAD

**Issue by ericclemmons** [zeit/err-redirect#8]
Can we keep:

> Warning: <title> should not be used in _document.js's <Head>. https://err.sh/next.js/no-document-title

But allow for override the org part of the param:

> Warning: You included React twice! https://err.sh/facebook/react/duplicate-react-instances

**Comment by j-f1** [comment]
That already works!

**Comment by ericclemmons** [comment]
Oh man, I'm sorry!  I did a test example and fudged the path 🤦‍♂️

Thanks your patience.
